server:
  port: 8080


spring:
  # redis
  redis:
    host: 62.234.221.210
    port: 2088
    database: 0
    timeout: 1800000
    password: gYEewWLM1p
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间（负数表示没限制）
        max-idle: 5
        min-idle: 0
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/readChat?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 20020523
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  # 配置映射类所在的包名
  type-aliases-package: top.devinwang.readChat.mapper
  # 配置 mapper xml文件所在的路径
  mapper-locations: classpath:mapper/**/*.xml

# 设置 JWT 密钥和过期时间 过期时间为100年
jwt:
  expire: 3075840000000
  signKey: ojDIyCjvaE

# 微信的相关密钥
weixin:
  appid: 'wx825685dd56d3e091'
  secret: '74c4edbb3c7d3446ee440497c0b7c04f'